"""
Export helpers: turn a FairnessReport into JSON, Markdown, or HTML.

The same report JSON drives all three. The Markdown and HTML rendering
differ slightly between Executive and Technical modes, but only in
density, never in factual content.
"""

from __future__ import annotations

import html
import json
from datetime import datetime

from .schemas import FairnessReport, ReportMode, RiskLevel

# ---------------------------------------------------------------------------
# JSON
# ---------------------------------------------------------------------------


def to_json(report: FairnessReport, *, indent: int = 2) -> str:
    """Canonical JSON export. This is the format stored in BigQuery."""
    return report.model_dump_json(indent=indent)


# ---------------------------------------------------------------------------
# Markdown
# ---------------------------------------------------------------------------


_RISK_EMOJI = {
    RiskLevel.MINIMAL: "🟢",
    RiskLevel.LOW: "🟢",
    RiskLevel.MODERATE: "🟡",
    RiskLevel.HIGH: "🟠",
    RiskLevel.SEVERE: "🔴",
}


def to_markdown(report: FairnessReport) -> str:
    """Markdown export. Style depends on report.mode."""
    if report.mode == ReportMode.EXECUTIVE:
        return _markdown_executive(report)
    return _markdown_technical(report)


def _markdown_executive(report: FairnessReport) -> str:
    lines: list[str] = []
    lines.append(f"# Fairness Report (Executive)")
    lines.append("")
    lines.append(f"**Audit ID:** `{report.audit_id}`  ")
    lines.append(f"**Generated:** {_fmt_dt(report.generated_at)}  ")
    lines.append(
        f"**Risk level:** {_RISK_EMOJI[report.risk_level]} "
        f"{report.risk_level.value.upper()}"
    )
    lines.append("")
    lines.append("## Verdict")
    lines.append("")
    lines.append(report.plain_english_verdict)
    lines.append("")

    lines.append("## What we found")
    lines.append("")
    for i, f in enumerate(report.headline_findings, start=1):
        lines.append(
            f"**{i}. {f.title}** _(severity: {f.severity.value})_"
        )
        lines.append("")
        lines.append(f.explanation)
        lines.append("")

    if report.impacted_groups:
        lines.append("## Who is affected")
        lines.append("")
        for ig in report.impacted_groups:
            lines.append(
                f"- **{ig.group}** (within `{ig.attribute}`): "
                f"{ig.evidence}"
            )
        lines.append("")

    if report.mitigation_summary:
        m = report.mitigation_summary
        lines.append("## Did mitigation help?")
        lines.append("")
        lines.append(f"**Method:** {m.method}")
        lines.append("")
        lines.append(f"**Fairness change:** {m.fairness_improvement}")
        lines.append("")
        lines.append(f"**Cost to utility:** {m.utility_cost}")
        if m.residual_concerns:
            lines.append("")
            lines.append(f"**Still a concern:** {m.residual_concerns}")
        lines.append("")

    if report.policy_alignment:
        pa = report.policy_alignment
        lines.append("## Policy alignment")
        lines.append("")
        lines.append(
            f"Alignment with **{pa.document_name}**: "
            f"**{pa.alignment_verdict.upper()}**"
        )
        if pa.gaps:
            lines.append("")
            lines.append("Gaps identified:")
            for g in pa.gaps:
                lines.append(f"- {g}")
        lines.append("")

    lines.append("## What to do next")
    lines.append("")
    for rec in report.recommendations:
        lines.append(f"- **[{rec.priority}]** {rec.action} — {rec.rationale}")
    lines.append("")

    if report.caveats:
        lines.append("## Caveats")
        lines.append("")
        for c in report.caveats:
            lines.append(f"- {c}")
        lines.append("")

    lines.append("---")
    lines.append("_Generated by NyayaLens. Not a substitute for legal, ethical, "
                 "or regulatory review._")
    return "\n".join(lines)


def _markdown_technical(report: FairnessReport) -> str:
    lines: list[str] = []
    lines.append(f"# Fairness Report (Technical)")
    lines.append("")
    lines.append(f"**Audit ID:** `{report.audit_id}`  ")
    lines.append(f"**Generated:** {_fmt_dt(report.generated_at)}  ")
    lines.append(f"**Report version:** {report.report_version}  ")
    lines.append(
        f"**Risk level:** {_RISK_EMOJI[report.risk_level]} "
        f"{report.risk_level.value.upper()}"
    )
    lines.append("")
    lines.append("## Verdict")
    lines.append("")
    lines.append(report.plain_english_verdict)
    lines.append("")

    lines.append("## Headline findings")
    lines.append("")
    lines.append("| # | Finding | Severity | Metric | Value | Threshold |")
    lines.append("|---|---------|----------|--------|-------|-----------|")
    for i, f in enumerate(report.headline_findings, start=1):
        lines.append(
            f"| {i} | {f.title} | {f.severity.value} | "
            f"{f.metric_name or ''} | "
            f"{_fmt_num(f.metric_value)} | "
            f"{_fmt_num(f.threshold_used)} |"
        )
    lines.append("")

    lines.append("### Finding details")
    lines.append("")
    for i, f in enumerate(report.headline_findings, start=1):
        lines.append(f"**{i}. {f.title}**")
        lines.append("")
        lines.append(f.explanation)
        lines.append("")

    if report.impacted_groups:
        lines.append("## Impacted groups")
        lines.append("")
        lines.append("| Attribute | Group | Harm type | Evidence |")
        lines.append("|-----------|-------|-----------|----------|")
        for ig in report.impacted_groups:
            lines.append(
                f"| `{ig.attribute}` | {ig.group} | {ig.harm_type} | "
                f"{ig.evidence} |"
            )
        lines.append("")

    if report.counterfactual_insight:
        lines.append("## Counterfactual analysis")
        lines.append("")
        lines.append(report.counterfactual_insight)
        lines.append("")

    if report.mitigation_summary:
        m = report.mitigation_summary
        lines.append("## Mitigation summary")
        lines.append("")
        lines.append(f"- **Method:** {m.method}")
        lines.append(f"- **Fairness improvement:** {m.fairness_improvement}")
        lines.append(f"- **Utility cost:** {m.utility_cost}")
        if m.residual_concerns:
            lines.append(f"- **Residual concerns:** {m.residual_concerns}")
        lines.append("")

    if report.tradeoffs:
        lines.append("## Tradeoffs")
        lines.append("")
        lines.append(report.tradeoffs)
        lines.append("")

    if report.policy_alignment:
        pa = report.policy_alignment
        lines.append("## Policy alignment")
        lines.append("")
        lines.append(f"- **Document:** {pa.document_name}")
        lines.append(f"- **Alignment verdict:** {pa.alignment_verdict}")
        if pa.rules_considered:
            lines.append("- **Rules considered:**")
            for r in pa.rules_considered:
                lines.append(f"  - {r}")
        if pa.gaps:
            lines.append("- **Gaps:**")
            for g in pa.gaps:
                lines.append(f"  - {g}")
        lines.append("")

    lines.append("## Recommendations")
    lines.append("")
    lines.append("| Priority | Owner | Action | Rationale |")
    lines.append("|----------|-------|--------|-----------|")
    for rec in report.recommendations:
        lines.append(
            f"| {rec.priority} | {rec.owner_hint or ''} | "
            f"{rec.action} | {rec.rationale} |"
        )
    lines.append("")

    if report.caveats:
        lines.append("## Caveats and limitations")
        lines.append("")
        for c in report.caveats:
            lines.append(f"- {c}")
        lines.append("")

    lines.append("---")
    lines.append(
        "_Generated by NyayaLens. Metrics are descriptive, not causal; "
        "fairness review requires human judgment._"
    )
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# HTML
# ---------------------------------------------------------------------------


def to_html(report: FairnessReport, *, embed_css: bool = True) -> str:
    """
    Minimal, self-contained HTML export. Useful for email embedding,
    screenshot prep, or as a preview in the Flutter web app.
    """
    title = (
        "Fairness Report (Executive)"
        if report.mode == ReportMode.EXECUTIVE
        else "Fairness Report (Technical)"
    )

    css = _DEFAULT_CSS if embed_css else ""

    body_parts: list[str] = []
    body_parts.append(f'<header class="nyaya-header">')
    body_parts.append(f'<h1>{html.escape(title)}</h1>')
    body_parts.append(
        f'<p><strong>Audit ID:</strong> <code>'
        f'{html.escape(report.audit_id)}</code></p>'
    )
    body_parts.append(
        f'<p><strong>Risk level:</strong> '
        f'<span class="risk risk-{report.risk_level.value}">'
        f'{html.escape(report.risk_level.value.upper())}</span></p>'
    )
    body_parts.append('</header>')

    body_parts.append(f'<section><h2>Verdict</h2>')
    body_parts.append(f'<p>{html.escape(report.plain_english_verdict)}</p></section>')

    body_parts.append('<section><h2>Headline findings</h2><ol>')
    for f in report.headline_findings:
        body_parts.append(
            f'<li><strong>{html.escape(f.title)}</strong> '
            f'<em>({html.escape(f.severity.value)})</em><br>'
            f'{html.escape(f.explanation)}</li>'
        )
    body_parts.append('</ol></section>')

    if report.impacted_groups:
        body_parts.append('<section><h2>Impacted groups</h2><ul>')
        for ig in report.impacted_groups:
            body_parts.append(
                f'<li><strong>{html.escape(ig.group)}</strong> '
                f'(<code>{html.escape(ig.attribute)}</code>): '
                f'{html.escape(ig.evidence)}</li>'
            )
        body_parts.append('</ul></section>')

    if report.mitigation_summary:
        m = report.mitigation_summary
        body_parts.append(f'<section><h2>Mitigation</h2>')
        body_parts.append(
            f'<p><strong>{html.escape(m.method)}</strong>: '
            f'{html.escape(m.fairness_improvement)} '
            f'(utility cost: {html.escape(m.utility_cost)})</p></section>'
        )

    if report.policy_alignment:
        pa = report.policy_alignment
        body_parts.append('<section><h2>Policy alignment</h2>')
        body_parts.append(
            f'<p><strong>{html.escape(pa.document_name)}</strong>: '
            f'{html.escape(pa.alignment_verdict)}</p>'
        )
        if pa.gaps:
            body_parts.append('<ul>')
            for g in pa.gaps:
                body_parts.append(f'<li>{html.escape(g)}</li>')
            body_parts.append('</ul>')
        body_parts.append('</section>')

    body_parts.append('<section><h2>Recommendations</h2><ul>')
    for rec in report.recommendations:
        body_parts.append(
            f'<li><span class="pri pri-{rec.priority}">'
            f'{html.escape(rec.priority)}</span> '
            f'<strong>{html.escape(rec.action)}</strong> — '
            f'{html.escape(rec.rationale)}</li>'
        )
    body_parts.append('</ul></section>')

    if report.caveats:
        body_parts.append('<section><h2>Caveats</h2><ul>')
        for c in report.caveats:
            body_parts.append(f'<li>{html.escape(c)}</li>')
        body_parts.append('</ul></section>')

    body_parts.append(
        '<footer><small>Generated by NyayaLens on '
        f'{html.escape(_fmt_dt(report.generated_at))}.</small></footer>'
    )

    return (
        "<!doctype html>"
        '<html lang="en"><head><meta charset="utf-8">'
        f"<title>{html.escape(title)}</title>"
        f"<style>{css}</style></head><body>"
        + "".join(body_parts)
        + "</body></html>"
    )


_DEFAULT_CSS = """
body { font-family: -apple-system, system-ui, sans-serif; max-width: 820px;
  margin: 2rem auto; line-height: 1.5; color: #1a1a1a; padding: 0 1rem; }
h1 { border-bottom: 3px solid #0b57d0; padding-bottom: .3rem; }
h2 { color: #0b57d0; margin-top: 2rem; }
code { background: #f1f3f4; padding: 0.1rem 0.3rem; border-radius: 3px; }
.risk { padding: 0.15rem 0.5rem; border-radius: 4px; color: white; font-weight: 600; }
.risk-minimal, .risk-low { background: #1e8e3e; }
.risk-moderate { background: #f9ab00; color: #1a1a1a; }
.risk-high { background: #e8710a; }
.risk-severe { background: #d93025; }
.pri { font-size: 0.8rem; text-transform: uppercase; font-weight: 600;
  margin-right: 0.4rem; padding: 0.1rem 0.4rem; border-radius: 3px; }
.pri-immediate { background: #fce8e6; color: #c5221f; }
.pri-short_term { background: #feefc3; color: #b06000; }
.pri-long_term { background: #e8f0fe; color: #1967d2; }
footer { margin-top: 3rem; color: #5f6368; }
"""


# ---------------------------------------------------------------------------
# Small helpers
# ---------------------------------------------------------------------------


def _fmt_dt(dt: datetime) -> str:
    return dt.strftime("%Y-%m-%d %H:%M UTC")


def _fmt_num(x: float | None) -> str:
    if x is None:
        return ""
    return f"{x:.3f}"


# ---------------------------------------------------------------------------
# Convenience: export all three formats for persistence
# ---------------------------------------------------------------------------


def bundle_exports(report: FairnessReport) -> dict[str, str]:
    """Return dict keyed by format. Useful for storage_service writes."""
    return {
        "json": to_json(report),
        "markdown": to_markdown(report),
        "html": to_html(report),
    }
