name: Docs Check

on:
  push:
    paths:
      - "docs/**"
      - "README.md"
  pull_request:
    paths:
      - "docs/**"
      - "README.md"

jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: echo "Add docs checks later"
